name: Test Output from Reusable Workflow

on: 
  push:
    branches:
      - main

jobs:
  # Call the reusable workflow to generate an artifact names
  call-reusable-workflow:
    uses: pacific-devops/resuable/.github/workflows/reusable-artifact-name.yml@main  # Call the reusable workflow
  
  # Use the output from the reusable workflow
  use-artifact:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow  # Ensure this job depends on the reusable workflow
    steps:
      - name: Use the Artifact Name
        run: |
          echo "Artifact name from reusable workflow: ${{ needs.call-reusable-workflow.outputs.artifact_name }}"
