# .github/workflows/deploy-reusable.yaml
name: Deploy Reusable Workflow

on:
  workflow_call:
    inputs:
      domain:
        description: "Domain selected by the user (e.g.,JQRS)"
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set domain and team variables
      run: |
       actor="${{ github.actor }}"  # The user who triggered the workflow
       org="your-org-name"  # Replace with your organization name
       team_slug="jira-developer"  # Example team slug

       # Make the API call to check team membership
        response=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
         https://api.github.com/orgs/$org/teams/$team_slug/memberships/$actor)

        # Print the entire response for debugging (optional)
        echo "API Response: $response"

        # Extract the role from the response
       membership_role=$(echo $response | jq -r '.role')

        if [[ "$membership_role" == "member" || "$membership_role" == "maintainer" ]]; then
       echo "$actor is part of the $team_slug team with role: $membership_role. Proceeding."
        echo "is_member=true" >> $GITHUB_ENV
       else
        echo "$actor is not a member of the $team_slug team, aborting."
        echo "is_member=false" >> $GITHUB_ENV
        exit 1
       fi
