# .github/workflows/deploy-reusable.yml
name: Deploy Reusable Workflow

on:
  workflow_call:
    inputs:
      domain:
        description: "Domain selected by the user (e.g., JQRS)"
        required: true
        type: string

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set team slug based on domain input
      run: |
        domain="${{ inputs.domain }}"
        team_slug="${domain}-developer"
        echo "Team slug set to: $team_slug"
        echo "team_slug=$team_slug" >> $GITHUB_ENV

    - name: Check if user is part of the selected team
      id: check_team_membership
      run: |
       user=${{ github.actor }}
       team_slug=$team_slug
       org="pacific-devops"

        # Fetch all the teams the user belongs to
        response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/orgs/$org/teams/$team_slug/memberships/$user)

        # Print the raw API response for debugging
        echo "API Response: $response"

        # Debug the response structure
         echo $response | jq '.'

        # Check membership state in the response
        membership_state=$(echo $response | jq -r '.state')

       if [ "$membership_state" != "active" ]; then
        echo "$user is not a member of the $team_slug team, aborting."
        echo "is_member=false" >> $GITHUB_ENV
       else
         echo "$user is an active member of the $team_slug team, proceeding with deployment."
         echo "is_member=true" >> $GITHUB_ENV
        fi

    - name: Deploy artifacts to JFrog
      if: env.is_member == 'true'
      run: |
        domain="${{ inputs.domain }}"
        jf rt upload --repo=my-jfrog-repo/$domain --url=$JF_URL
