# .github/workflows/deploy-reusable.yml
name: Deploy Reusable Workflow

on:
  workflow_call:
    inputs:
      domain:
        description: "Domain selected by the user (e.g.,JQRS)"
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set team slug based on domain input
      run: |
        domain="${{ inputs.domain }}"
        team_slug="${domain}-developer"
        echo "Team slug set to: $team_slug"
        echo "team_slug=$team_slug" >> $GITHUB_ENV

    - name: Check if user is part of the selected team
      id: check_team_membership
      run: |
        org="pacific-devops"
        response=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
        https://api.github.com/orgs/$org/teams)

        echo "Teams in the organization:"
        echo $response | jq '.'

    - name: Deploy artifacts to JFrog
      if: env.is_member == 'true'
      run: |
        domain="${{ inputs.domain }}"
        jf rt upload --repo=my-jfrog-repo/$domain --url=$JF_URL
