# .github/workflows/deploy-caller.yml
name: Deploy Caller

on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  call-deploy:
    uses: ./.github/workflows/generic.yaml
    with:
      domain: jira




        
