# .github/workflows/deploy-reusable.yml
name: Deploy Reusable Workflow

on:
  workflow_call:
    inputs:
      domain:
        description: "Domain selected by the user (e.g.,JQRS)"
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set domain and team variables
      run: |
        domain="${{ inputs.domain }}"
        team_slug="${domain}-developer"  # Construct the team slug dynamically
        actor="${{ github.actor }}"  # The user who triggered the workflow
        org="your-org-name"  # Replace with your organization name

        echo "Checking if $actor is part of the $team_slug team."
        echo "domain=$domain" >> $GITHUB_ENV
        echo "team_slug=$team_slug" >> $GITHUB_ENV
        echo "actor=$actor" >> $GITHUB_ENV
        echo "org=$org" >> $GITHUB_ENV

    - name: Check if user is part of the team
      run: |
        response=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
        https://api.github.com/orgs/$org/teams/$team_slug/memberships/$actor)

        membership_state=$(echo $response | jq -r '.state')

        if [[ "$membership_state" != "active" ]]; then
          echo "$actor is not a member of the $team_slug team, aborting."
          exit 1
        else
          echo "$actor is an active member of the $team_slug team, proceeding with deployment."
        fi
