# .github/workflows/deploy-reusable.yml
name: Deploy Reusable Workflow

on:
  workflow_call:
    inputs:
      domain:
        description: "Domain selected by the user (e.g.,JQRS)"
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Verify if GH_PAT is set correctly
      run: |
        if [ -z "${{ secrets.GH_PAT }}" ]; then
          echo "The GH_PAT secret is not set!"
          exit 1
        else
          echo "GH_PAT secret is accessible."
        fi
    - name: Set repository and user variables
      run: |
        repo_full_name="${{ github.repository }}"  # Automatically gets owner/repo
        owner=$(echo $repo_full_name | cut -d'/' -f1)
        repo=$(echo $repo_full_name | cut -d'/' -f2)
        actor="${{ github.actor }}"  # The user who triggered the workflow
        echo "owner=$owner" >> $GITHUB_ENV
        echo "repo=$repo" >> $GITHUB_ENV
        echo "actor=$actor" >> $GITHUB_ENV

    - name: List teams with access to the repository
      run: |
        response=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
        https://api.github.com/repos/$owner/$repo/teams)

        echo "Teams with access to the repository:"
        echo $response | jq '.'
