# .github/workflows/deploy-reusable.yaml
name: Deploy Reusable Workflow

on:
  workflow_call:
    inputs:
      domain:
        description: "Domain selected by the user (e.g.,JQRS)"
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set domain and team variables
      run: |
       actor="${{ github.actor }}"  # The user to check
       org="pacific-devops"  # Your organization name
       team_slug="${{inputs.domain}}-developer"  # The team slug

       # Make the API call to list team members
       response=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
        https://api.github.com/orgs/$org/teams/$team_slug/members)

        # Check if the user is part of the team by searching for their login
        is_member=$(echo $response | jq --arg actor "$actor" '.[] | select(.login == $actor)')

       if [ -z "$is_member" ]; then
        echo "$actor is not part of the $team_slug team, aborting."
        exit 1
       else
        echo "$actor is part of the $team_slug team, proceeding."
        echo "is_member=true" >> $GITHUB_ENV
       fi
