# .github/workflows/deploy-reusable.yml
name: Deploy Reusable Workflow

on:
  workflow_call:
    inputs:
      domain:
        description: "Domain selected by the user (e.g.,JQRS)"
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Set organization name
       run: |
        org_name="pacific-devops"  # Replace with your organization name
        echo "org_name=$org_name" >> $GITHUB_ENV

     - name: List all teams at the organization level
       run: |
        org="${{ env.org_name }}"
        response=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
        https://api.github.com/orgs/$org/teams)

        echo "Teams in the organization:"
        echo $response | jq '.'
