# .github/workflows/deploy-caller.yml
name: Deploy Caller

on:
  push:
    branches:
      - main

jobs:
  call-deploy:
    uses: ./.github/workflows/generic.yaml
    with:
      domain: jira




        
