name: Java Maven Build and Test

on:
 workflow_call:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11 (you can change the version if necessary)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'


      # Step 4: Change directory to my-calculator and build the project
      - name: Build with Maven
        run: |
          cd myCalculator
          mvn clean install

      # Step 5: Change directory to my-calculator and run tests
      - name: Run Tests with Maven
        run: |
          cd myCalculator
          mvn clean test
      - name: Build with Maven and Generate JaCoCo Report
        run: |
          cd myCalculator
          mvn clean verify # 'verify' will run tests and generate th
      - name: SonarQube Scan Maven
        id: execute-sonarqube-scan-maven
        if: always()
        run: |
          # shellcheck disable=2086
          {
            cd myCalculator
      
            mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.organization=pacific-devops \
              -Dsonar.projectKey=pacific-devops_Hello_master \
              -Dsonar.sources=src/main \
              -Dsonar.tests=src/test \
              -Dsonar.verbose=true \
              -Pcoverage -X
          }
        # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        with:
           scanMetadataReportFile: myCalculator/target/sonar/report-task.txt
